# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qt/main.ui'
#
# Created: Thu Jan 15 22:44:27 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(367, 390)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(367, 390))
        Form.setMaximumSize(QtCore.QSize(367, 390))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.frame_3 = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.video_first_frame = QtGui.QLineEdit(self.frame_3)
        self.video_first_frame.setReadOnly(True)
        self.video_first_frame.setObjectName(_fromUtf8("video_first_frame"))
        self.horizontalLayout_2.addWidget(self.video_first_frame)
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.video_last_frame = QtGui.QLineEdit(self.frame_3)
        self.video_last_frame.setReadOnly(True)
        self.video_last_frame.setObjectName(_fromUtf8("video_last_frame"))
        self.horizontalLayout_2.addWidget(self.video_last_frame)
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.video_audio = QtGui.QLineEdit(self.groupBox)
        self.video_audio.setReadOnly(True)
        self.video_audio.setObjectName(_fromUtf8("video_audio"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.video_audio)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.frame_4 = QtGui.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.video_id = QtGui.QComboBox(self.frame_4)
        self.video_id.setObjectName(_fromUtf8("video_id"))
        self.horizontalLayout_4.addWidget(self.video_id)
        self.btn_refresh_list = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refresh_list.sizePolicy().hasHeightForWidth())
        self.btn_refresh_list.setSizePolicy(sizePolicy)
        self.btn_refresh_list.setObjectName(_fromUtf8("btn_refresh_list"))
        self.horizontalLayout_4.addWidget(self.btn_refresh_list)
        self.video_delete_btn = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_delete_btn.sizePolicy().hasHeightForWidth())
        self.video_delete_btn.setSizePolicy(sizePolicy)
        self.video_delete_btn.setObjectName(_fromUtf8("video_delete_btn"))
        self.horizontalLayout_4.addWidget(self.video_delete_btn)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_4)
        self.frame_2 = QtGui.QFrame(self.groupBox)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.video_path = QtGui.QLineEdit(self.frame_2)
        self.video_path.setEnabled(True)
        self.video_path.setReadOnly(True)
        self.video_path.setObjectName(_fromUtf8("video_path"))
        self.horizontalLayout.addWidget(self.video_path)
        self.btn_select_path = QtGui.QPushButton(self.frame_2)
        self.btn_select_path.setObjectName(_fromUtf8("btn_select_path"))
        self.horizontalLayout.addWidget(self.btn_select_path)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.frame = QtGui.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.video_fps = QtGui.QLineEdit(self.frame)
        self.video_fps.setReadOnly(True)
        self.video_fps.setObjectName(_fromUtf8("video_fps"))
        self.horizontalLayout_3.addWidget(self.video_fps)
        self.fps_auto = QtGui.QCheckBox(self.frame)
        self.fps_auto.setChecked(True)
        self.fps_auto.setTristate(False)
        self.fps_auto.setObjectName(_fromUtf8("fps_auto"))
        self.horizontalLayout_3.addWidget(self.fps_auto)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.video_bitrate = QtGui.QLineEdit(self.groupBox_2)
        self.video_bitrate.setObjectName(_fromUtf8("video_bitrate"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.video_bitrate)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.frame_5 = QtGui.QFrame(self.groupBox_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.file_id = QtGui.QLabel(self.frame_5)
        self.file_id.setObjectName(_fromUtf8("file_id"))
        self.horizontalLayout_5.addWidget(self.file_id)
        self.video_render_name = QtGui.QLineEdit(self.frame_5)
        self.video_render_name.setObjectName(_fromUtf8("video_render_name"))
        self.horizontalLayout_5.addWidget(self.video_render_name)
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.frame_5)
        self.frame_6 = QtGui.QFrame(self.groupBox_2)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btn_render_all = QtGui.QPushButton(self.frame_6)
        self.btn_render_all.setEnabled(False)
        self.btn_render_all.setObjectName(_fromUtf8("btn_render_all"))
        self.horizontalLayout_6.addWidget(self.btn_render_all)
        self.btn_render = QtGui.QPushButton(self.frame_6)
        self.btn_render.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_render.sizePolicy().hasHeightForWidth())
        self.btn_render.setSizePolicy(sizePolicy)
        self.btn_render.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_render.setObjectName(_fromUtf8("btn_render"))
        self.horizontalLayout_6.addWidget(self.btn_render)
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.SpanningRole, self.frame_6)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.frame_7 = QtGui.QFrame(self.groupBox_2)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.video_cmd_line = QtGui.QLineEdit(self.frame_7)
        self.video_cmd_line.setObjectName(_fromUtf8("video_cmd_line"))
        self.horizontalLayout_7.addWidget(self.video_cmd_line)
        self.video_cmd_default = QtGui.QCheckBox(self.frame_7)
        self.video_cmd_default.setChecked(True)
        self.video_cmd_default.setObjectName(_fromUtf8("video_cmd_default"))
        self.horizontalLayout_7.addWidget(self.video_cmd_default)
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.frame_7)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.frame_8 = QtGui.QFrame(self.groupBox_2)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.video_render_path = QtGui.QLineEdit(self.frame_8)
        self.video_render_path.setReadOnly(True)
        self.video_render_path.setObjectName(_fromUtf8("video_render_path"))
        self.horizontalLayout_8.addWidget(self.video_render_path)
        self.btn_select_render_path = QtGui.QPushButton(self.frame_8)
        self.btn_select_render_path.setObjectName(_fromUtf8("btn_select_render_path"))
        self.horizontalLayout_8.addWidget(self.btn_select_render_path)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_8)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "renderb0x", None))
        self.groupBox.setTitle(_translate("Form", "Input", None))
        self.label.setText(_translate("Form", "Frames:", None))
        self.label_5.setText(_translate("Form", "-", None))
        self.label_3.setText(_translate("Form", "Audio:", None))
        self.label_6.setText(_translate("Form", "Path:", None))
        self.label_7.setText(_translate("Form", "ID:", None))
        self.btn_refresh_list.setText(_translate("Form", "Refresh", None))
        self.video_delete_btn.setText(_translate("Form", "Delete", None))
        self.btn_select_path.setText(_translate("Form", "Select Path", None))
        self.groupBox_2.setTitle(_translate("Form", "Output", None))
        self.label_2.setText(_translate("Form", "FPS:", None))
        self.fps_auto.setText(_translate("Form", "Auto", None))
        self.label_4.setText(_translate("Form", "Bitrate:", None))
        self.label_8.setText(_translate("Form", "Filename:", None))
        self.file_id.setText(_translate("Form", "id_", None))
        self.label_9.setText(_translate("Form", ".mp4", None))
        self.btn_render_all.setText(_translate("Form", "Render All", None))
        self.btn_render.setText(_translate("Form", "Render", None))
        self.label_10.setText(_translate("Form", "cmd line:", None))
        self.video_cmd_default.setText(_translate("Form", "Default", None))
        self.label_11.setText(_translate("Form", "Path:", None))
        self.btn_select_render_path.setText(_translate("Form", "Select Path", None))

